### ISSUE TITLE
EXTREMELY IMPORTANT

### ISSUE THREAD

**Issue by vi1r** [enkhee-Osiris/Decoder-JSFuck#2]
this sites main box is vulnerable to js injection

**Comment by sportshead** [comment]
What do you mean by JS injection? The whole point of the site is too decode JS, you're putting JS in yourself

**Comment by enkhee-Osiris** [comment]
@darkerhaunter hey, can you explain more. Is it about `eval()` function?

**Comment by enkhee-Osiris** [comment]
Feel free to re-open
